# Generated by Django 2.2.5 on 2021-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210527_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=255, null=True, verbose_name='头像'),
        ),
    ]
