# Generated by Django 2.2.5 on 2021-06-06 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='WorkCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code_status', models.IntegerField(choices=[(1, '使用'), (0, '未使用')], default=1)),
                ('user_id', models.IntegerField(verbose_name='收藏者id')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.WorkImg', verbose_name='收藏作品')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'db_table': 'tb_work_collections',
            },
        ),
    ]
